#!/usr/bin/env ruby

#
# This script exercises the 'arm tracks' MMC command, in order to determine
# the proper track bitmap.
#

require 'unimidi'

require_relative '../lib/midi-mmc'

midi_output = UniMIDI::Output.gets
mmc = MIDI::MMC.new(output: midi_output, debug: true)

mmc.reset

begin
  1.upto(24).each do |track|
    mmc.write(nil)
    msg = mmc.arm_tracks(track)
    pp(track => msg)
    gets
  end
ensure
  mmc.arm_tracks(nil)
  mmc.reset
end